"""
bls/definability/oracle/closure.py — the recognizer: the closed enriched monoid.

Materializes `EM¹(D)` — the acceptance-enriched monoid of a deterministic
completed automaton, with the identity adjoined — by BFS from the letter
elements under right-multiplication, up to a size budget. The result carries
everything the congruence computation consumes downstream: the element set,
one shortest representative word per element, and the right-multiplication
table `element × letter → element`.

Pure: the budget is a parameter, blowing it returns `None` (the caller owns
the policy of what that means).
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Optional

from ..witness.enriched import Elem, compose


@dataclass
class Monoid:
    """The closed enriched monoid `EM¹(D)`, indexed form.

    Element 0 is the identity (the empty word). `rep[i]` is a shortest word
    for element `i`, as 0-based letter indices into the generator order the
    closure was built from. `right[i][l]` is the index of `elems[i] · letter l`
    — total over all elements and letters."""

    elems: List[Elem]
    index: Dict[Elem, int]
    rep: List[List[int]]
    right: List[List[int]]

    def __len__(self) -> int:
        return len(self.elems)

    def mult(self, i: int, j: int) -> int:
        """The index of `elems[i] · elems[j]` (one `O(|Q|·|rep[j]|)`-free
        composition: the elements themselves compose in `O(|Q|)`)."""
        return self.index[compose(self.elems[i], self.elems[j])]


def close(letters: List[Elem], n_states: int, cap: int) -> Optional[Monoid]:
    """BFS-close the monoid generated by `letters` (identity adjoined), keeping
    one shortest representative per element, or `None` when more than `cap`
    elements appear. Representatives are enumerated shortest-first, so element
    order is BFS order."""
    identity: Elem = tuple((q, frozenset()) for q in range(n_states))
    elems: List[Elem] = [identity]
    index: Dict[Elem, int] = {identity: 0}
    rep: List[List[int]] = [[]]
    right: List[List[int]] = []
    i = 0
    while i < len(elems):
        row: List[int] = []
        for li, le in enumerate(letters):
            ne = compose(elems[i], le)
            j = index.get(ne)
            if j is None:
                if len(elems) >= cap:
                    return None
                j = len(elems)
                index[ne] = j
                elems.append(ne)
                rep.append(rep[i] + [li])
            row.append(j)
        right.append(row)
        i += 1
    return Monoid(elems=elems, index=index, rep=rep, right=right)


__all__ = ["Monoid", "close"]
