"""
bls/gap/witness_group.py — the witness-only GAP script (non-LTL witness material).

The aperiodicity oracle (`gap/aperiodic.py`) answers one boolean. When a language
is NOT LTL-definable its transition monoid carries a non-trivial group, and a
*witness* needs that group made concrete. This script finds, in the transition
semigroup generated by the letter images, a non-trivial **group H-class** (Green's
theory: exactly what a non-aperiodic semigroup contains), picks a non-identity
element `g` of that group, computes its order `p > 1` (the period), and returns a
`Factorization` of `g` over the monoid generators — a word in generator indices the
caller lifts back to concrete letters.

A new sibling of `gap/aperiodic.py`; it reuses the stable GAP infrastructure
(`run_gap_script`, `_format_transformation`) read-only, modifying nothing.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional

from .export import _format_transformation
from .runner import run_gap_script


@dataclass
class RawWitness:
    """The raw witness material GAP returns: the period and the factorization of the
    group element over the monoid generators (1-based generator indices)."""

    period: int
    factor: List[int]


def _witness_script(generators: List[List[int]]) -> str:
    """A self-contained GAP/Semigroups script: build the semigroup, find a
    non-trivial group H-class, factorize one non-identity element of it."""
    body = ",\n    ".join(_format_transformation(g) for g in generators)
    return (
        '# Auto-generated by BuchiToLTL/bls/gap/witness_group.py (non-LTL witness).\n'
        'LoadPackage("Semigroups");\n'
        f'gens := [\n    {body}\n];\n'
        'S := Semigroup(gens);\n'
        'hs := Filtered(GreensHClasses(S), h -> IsGroupHClass(h) and Size(h) > 1);\n'
        'if Length(hs) = 0 then\n'
        '    Print("NOWITNESS\\n");\n'
        'else\n'
        '    h := hs[1];\n'
        '    e := First(Elements(h), x -> x * x = x);\n'      # the group H-class identity
        '    g := First(Elements(h), x -> x <> e);\n'         # a non-identity element
        '    p := 1; t := g;\n'
        '    while t <> e do t := t * g; p := p + 1; od;\n'   # order of g in the group
        '    Print("PERIOD: ", p, "\\n");\n'
        '    Print("FACTOR: ", Factorization(S, g), "\\n");\n'
        'fi;\n'
        'QUIT;\n'
    )


def witness_group(
    generators: List[List[int]],
    *,
    gap_cmd: str = "gap",
    timeout: int = 60,
) -> Optional[RawWitness]:
    """Return a `RawWitness` (period + factorization over the generators) for the
    non-trivial group in the transition semigroup, or `None` if there is no group
    (an aperiodic input — the gate should have caught it first).

    `generators` is the list-of-images representation `extract_generators` produces.
    Raises `RuntimeError` if GAP reports neither a witness nor `NOWITNESS`.
    """
    if not generators:
        raise ValueError("at least one generator is required")
    raw = run_gap_script(
        _witness_script(generators), gap_cmd=gap_cmd, timeout=timeout
    )
    period: Optional[int] = None
    factor: Optional[List[int]] = None
    for line in raw.splitlines():
        if "NOWITNESS" in line:
            return None
        if line.startswith("PERIOD:"):
            period = int(line.partition(":")[2].strip())
        elif line.startswith("FACTOR:"):
            inside = line.partition(":")[2].strip().strip("[]")
            factor = [int(tok) for tok in inside.replace(" ", "").split(",") if tok]
    if period is None or factor is None:
        raise RuntimeError(
            f"witness GAP reported no PERIOD/FACTOR; output:\n{raw[:400]}"
        )
    return RawWitness(period=period, factor=factor)


__all__ = ["RawWitness", "witness_group"]
